### ISSUE TITLE
Wfrecord modules

### ISSUE THREAD

**Issue by kaiserdev59** [ldelossa/dotfiles#2]
I really love your waybar's modules, but how can I use these modules in waybar/module ? 😅
![Screenshot_2023-06-09-21-22-25_22693](https://github.com/ldelossa/dotfiles/assets/107534756/ac278396-97e8-4b67-b9f0-debb16c7ee62)

**Comment by ldelossa** [comment]
Hey there, 

Check out an older waybar config, I don't use those modules anymore :) 

https://github.com/ldelossa/dotfiles/blob/15998ffb8b8bc37f1817297e0c8588f5d2d0a6a4/config/waybar/config
